name: CI/CD Pipeline Manual with threads
on:
  workflow_dispatch:
    inputs:
      threads: 
        description: Threads to run on
        required: true
        type: choice
        default: '1'
        options:
          - '1'
          - '2'
          - '4'
          
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
            
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx wdio run wdio${{ inputs.threads }}.conf.js
        env:
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
